version: '3'
services:
    frp:
        build: .
        image: xyzrlee/frp
        restart: unless-stopped
        volumes:
            - .:/conf:ro
        entrypoint: frps
        ports:
            - 7000:7000/tcp
        command: -c /conf/frps.ini
